### ISSUE TITLE
Support computed properties

### ISSUE THREAD

**Issue by LSX-s-Software** [Events-Mate-Apps/SimpleCodableMacro#1]
Your macro is brilliant! However, this macro will generate code that encodes and decodes the **computed properties**, which is incorrect as those properties are not stored and cannot be initialized.

**Comment by Events-Mate-Apps** [comment]
Great point I usually used computed properties outside of my class like so 

```
@Codable
class Foo {
    var fooName: String
}

extension Foo {
    var fooSuperName: String {
        "Super " + fooName
    }
}
```
